### ISSUE TITLE
PythoStitcher Docker container

### ISSUE THREAD

**Issue by swik4567** [computationalpathologygroup/pythostitcher#1]
How do I get the docker container for pythostitcher?

**Comment by dnschouten** [comment]
EDIT: You can now pull the docker from GHCR using the following command:
`docker pull ghcr.io/computationalpathologygroup/pythostitcher:latest`

---------------------------------------------------------------------------------------

For now you can download the Docker container (.tar) through [SURF's filesender](https://filesender.surf.nl/?s=download&token=708ac00a-d2ce-4576-acf9-366c940de051). Eventually we'd like to host our container on a public container repository, but that's still work in progress. 

Please note that PythoStitcher is still in alpha stage and is still actively being developed, so please do let me know if you run into any issues so I can have a look.
