### ISSUE TITLE
Speed up the process

### ISSUE THREAD

**Issue by zaynah91124** [computationalpathologygroup/pythostitcher#6]
Hello, I would like to ask if putting the inference process on GPU will speed up the process? Have you ever done related operations?

**Comment by dnschouten** [comment]
Hi @zaynah91124, which parts would you like to speed up? Can you share some stats on how fast it currently runs for your use case? If you save the images at full resolution, ~95% of execution time is spent saving the stitched image to disk. If you don't require the stitched images to be at full resolution, choosing a lower resolution will greatly speed things up.

**Comment by dnschouten** [comment]
Closing this as stale - feel free to reopen if you require further help here.
